name: Java CI with Gradle

on:
  schedule:
    - cron: "30 12 * * 3"
    - cron: "0 22 * * 5"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
      contents: read
      checks: write
      actions: read
      
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: [11, 13, 17]
        include:
          - java-version: 11
          - java-version: 13
          - java-version: 17
      fail-fast: false

    name: Build - Java ${{ matrix.java-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
        gradle-version: '8.9'
        
    - name: Build with Gradle
      run: ./gradlew build

  test:
    needs: build
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: [11, 13, 17]
        include:
          - java-version: 11
          - java-version: 13
          - java-version: 17
      fail-fast: false

    name: Test - Java ${{ matrix.java-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
        gradle-version: '8.9'
      
    - name: Run tests
      run: ./gradlew test

    - name: Test Report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: JUnit Test Results - Java ${{ matrix.java-version }} on ${{ matrix.os }}
        path: '**/build/test-results/test/*.xml'
        reporter: 'java-junit'
        fail-on-error: false
        only-summary: false
